### ISSUE TITLE
Canvas overlays needs HiDPI fixes

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#105]
The canvas overlays don't work with HiDPI.

**Comment by kaixoo** [comment]
Can you be more detailed in your issues? It takes me some effort to understand the issue. What is necessary to reproduce the issue? What's causing it? How should it behave?

**Comment by rodlie** [comment]
Issues I create are mostly for my own reference, so they might be lacking, just ask if this is something you want to work on etc.

This issue tracks the progress of fixing the canvas overlays for hidpi, currently node points, pivot points etc don't scale as they should (they are too tiny), it's a matter of adding pixel ratio where needed.

Not a big issue, but should be looked at before next release.

**Comment by kaixoo** [comment]
Can we chat?

**Comment by rodlie** [comment]
I got a fix (minimal testing on Linux/X11 with 4k 200%), will check Windows etc later today.

### Before

![Screenshot from 2024-10-18 13-31-11](https://github.com/user-attachments/assets/c027722d-c345-4940-9c87-cf980ada14c7)

### After

![Screenshot from 2024-10-18 13-31-33](https://github.com/user-attachments/assets/5ecd1b33-f819-482f-a9e9-94bdb8bd0e0f)

**Comment by rodlie** [comment]
fixed.
