### ISSUE TITLE
Mouse right button click problem

### ISSUE THREAD

**Issue by YasinC2** [friction2d/friction#115]
in "Properties" panel and objects layers panel when i click right mouse button (MRB), the context menu will open and select first option which is path effects and then close. but when i click MRB and move the mouse to other direction before release the button and then release the MRB, context menu remain open and i can use menu options.

I test this problem with two different mouse, so the problem isn't from mouse.

Tested on:
Version: 0.9.4 & 0.9.5
Platform: Windows

**Comment by rodlie** [comment]
Hi,

This is a known issue that happens on Windows. I believe it's related to Qt (the UI framework we use).

A simple update of Qt should in theory (famous last words) fix the issue (#110). I should have time to test this this weekend.

**Comment by rodlie** [comment]
Should be fixed in 0.9.6, I don't notice anything on Windows anymore. Please reopen if 0.9.6 don't fix this issue.
