### ISSUE TITLE
Bugs, suggestions, and thanks!

### ISSUE THREAD

**Issue by PsychoTAL** [friction2d/friction#119]
Hello! I'm new, but I'll do my best. 
I use Windows 10 Pro version 22H2
Processor : Intel Core i7 CPU Q720 1.60 GHz
Installed RAM: 8 GB
VRAM : 1 GB

1. BUG 1 : When you create a linked group via "Action/Create Link" (it has to be a group, not a simple path), the program crash immediately when you put that linked group (the duplicate) inside the group it was linked to (the original). I understand this is something that should happen (and very dumb to do), but instead of crashing, the program should warn and/or cancel the action.
![G](https://github.com/friction2d/friction/assets/95470595/5185578c-5eca-40fb-9a45-936cbffe6741)

2. BUG 2 : I don't know if this is really a bug but when in "node edit mode" or "Point", the shortcut "P" does not trigger the "Pivot global/local", you have to manually click it on the toolbar.
![F](https://github.com/friction2d/friction/assets/95470595/4c924478-379d-41d1-b5b4-f219a8768866)

3. BUG 3 : This was there since Enve2D; after rendering a scene, closing the program, then reopening the last scene that I rendered, the name of the scene in the "Queue" tab becomes "-none-", but goes back to the scene name again when changing the settings of the rendering output.
![N](https://github.com/friction2d/friction/assets/95470595/0821a0aa-e33c-459e-aa83-0c4fe694277a)

4. BUG 4 : When clicking the "Pick color" in the "Fill and Stroke" tab, the entire screen blinks for a short moment. This does not happen when clicking the "Pick" in the toolbar on the leftmost part.

5. SUGGESTION 1 : This might just be for me, but when entering or leaving "Point" mode, all the node operations (Merge nodes, etc.) appear/disappear and move the entire canvas. The moving of the canvas can be quite jarring when you use the "Point" mode often (for me at least). Just a suggestion, like making the "node operation" a floating tab that does not affect the canvas position, like the one on blender when you press "T".

6. SUGGESTION 2 : Bookmarking a color should have a shortcut, like "B" maybe.

That's all I could find for now.
Thank you very much for all the contributors in the development of Enve2D and Friction2D.
I wish you all the best!

**Comment by rodlie** [comment]
Thanks for your feedback :+1: 

I'm currently busy with other projects at the moment, but will get back to you by the end of this week.

**Comment by PsychoTAL** [comment]
Thanks for the hard work.
Wish you all the best!

**Comment by rodlie** [comment]
Sorry for the late reply (as usual :P )

bug 1 and 2 has been fixed.

I know about bug 3, but it hasn't been annoying enough to fix yet :)  but I will take a look at the problem.

4. Yes, the "Fill and stroke" picker takes a screenshot of the entire screen and pick the color from that. This comes from enve and is something that should be refactored (I don't know the reason for this). The "regular" color picker takes the color(s) from the actual object(s).

5. I'm currently doing some (local) UI layout changes and will try to figure out a better solution for the toolbar while I'm fixing other stuff.

6. Ok, will add

**Comment by rodlie** [comment]
Regarding .5


https://github.com/friction2d/friction/assets/34516798/ca291b2f-2373-4990-98a5-61a223b44633

**Comment by PsychoTAL** [comment]
Hello!

You just solved 90% of all my issues with Friction2D! (you may already know that I posted another report, but those are not crashing/breaking bugs that need immediate actions, in my opinion at least.)

Thanks for considering ALL my suggestions. The solution for "5" works pretty fine with me!

Spoiler for "Friction2D 0.9.6" !? Are you making the tabs (Fill and Stroke, etc.) dockable ?!

Anyway, I guess this post can definitely be closed now!

Thanks for everything, and wish you the best!
