### ISSUE TITLE
Flatpak requires an already-installed runtime

### ISSUE THREAD

**Issue by mikwee** [friction2d/friction#124]
When trying to install the Flatpak on Fedora 39 (which afaik is compatible with RHEL), I get this error: `error: The application graphics.friction.Friction/x86_64/master requires the runtime org.freedesktop.Sdk/x86_64/23.08 which was not found`. When trying to install that runtime with Flatpak, I see that it is already installed. This issue only happens with Flatpak. Why could that be?

Thanks.

**Comment by rodlie** [comment]
Could it be an issue with system vs. --user installed flatpak(s)?

I don't have much experience with Flatpaks in general, I tested the flatpak on two different distros before release and it worked, that's pretty much all info I got :)

I will submit the flatpak to flathub soonish, that should resolve issues like this(?).
