### ISSUE TITLE
RPM : Binary don't link to correct lib folder

### ISSUE THREAD

**Issue by mikwee** [friction2d/friction#125]
I see this error occurs with other programs as well. In those cases, they had to be patched.

This error happens whenever I try to open Friction. I'm on Fedora 39. I could use help.

Thanks.

**Comment by rodlie** [comment]
Portable tarball, Flatpak, AppImage?

**Comment by mikwee** [comment]
RPM.

**Comment by rodlie** [comment]
Seems like the RPM has a broken linker, sorry about that. Will fix.

Please use the portable tarball or the AppImage until the RPM is fixed.

**Comment by rodlie** [comment]
Workaround for RPM : `LD_LIBRARY_PATH=../lib ./friction`
