### ISSUE TITLE
Friction 0.9.6 release

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#126]
This issue tracks the progress of Friction 0.9.6.

- [x] Feature freeze
- [x] Update SDK
  - [x] Update to Qt 5.15.13
    - [x] Windows
    - [x] Linux
  - [x] Remove dependency on Windows Media Foundation (Support Windows N)
- [x] **Beta** (2024-04-27)
  - [x] Build source snapshot
  - [x] Build Windows snapshot
  - [x] Build CentOS snapshot
  - [x] Build Ubuntu  snapshot
- [ ] **Release** (ETA 2024-06-18)
  - [x] Finish [Release Notes](https://github.com/friction2d/friction2d.github.io/blob/main/_drafts/friction-096.md)
  - [x] Make a (super) simple and short video for social media
    - Good way to find issues before release
  - [x] Release Candidate (2024-05-20)
    - [x] Build source snapshot
    - [x] Build Windows snapshot
    - [x] Build Linux snapshot
  - [x] Update to Qt 5.15.14
  - [x] Second Release Candidate (2024-05-26)
    - [x] Build source snapshot
    - [x] Build Windows snapshot
    - [x] Build Linux snapshot
  - [x] Build source release
  - [x] Build Windows release
  - [x] Build Linux release
  - [x] Update website
    - [x] Add release notes
    - [x] Update links to latest release

**Comment by PsychoTAL** [comment]
Hello!

I'm not really sure where should I put my feedback for "0.9.6 beta1", so I'll put it here for now.

Pressing "P" does not activate the Local/Global pivot.

Haven't found any regression/other issue so far.

Wish you the best!

**Comment by rodlie** [comment]
Thanks for testing and reporting :+1: 

I broke the shortcut when I changed the UI, it's now fixed.

**Comment by rodlie** [comment]
We might need to downgrade FFmpeg before release.

`Ignoring attempt to flush encoder that doesn't support it` has been with us since enve (and been ignored by me), but might be related to odd issues with the queue, something is not rendered or stalls. Downgrading FFmpeg from 4.4.x to 4.2.x seems to fix the issues (and no warning).

I know, workarounds instead of fixes, but I don't have time to review the encoding code at the moment. Will do some more tests and make a decision in a day or two.

Ref: https://github.com/orgs/friction2d/discussions/147

**Comment by rodlie** [comment]
> Will Friction be adding ORA import in this version?

No. See #89 

> Multi-layer import seems necessary for compositing software.

Yes, but Friction is not a compositing application.

**Comment by rodlie** [comment]
Been sick most of this week, so the release has been delayed to Saturday/Sunday.
