### ISSUE TITLE
Deleting in "Recent Files List" and Icon discussion  

### ISSUE THREAD

**Issue by PsychoTAL** [friction2d/friction#146]
Hello!

1- So, if the "Open Recent" file list contains some unavailable files (deleted, moved somewhere else, incompatible, etc.),
selecting those will just prompt an error message without deleting them in the list.
And there is no way (in my knowledge) to delete something in that list.
Possible options (in my opinion): 
- Deleting the entry after the error message
- Adding a way to delete something in the list, such as "Clear recent" ?

 2- About the Icon discussion:
![B](https://github.com/friction2d/friction/assets/95470595/481ae5ae-ae84-4106-92bf-b0cea514512e)
Left to the "graph", it is apparently the "Settings" for the timeline,
BUT it is essentially just a filter, right?
If it is, wouldn't it be more suitable to put a "Filter icon" instead of "Dots", which is by the way not very intuitive (again in my opinion)

That's all for now.
Wish you all the best!

**Comment by rodlie** [comment]
* Timeline "settings" are now filters (with a filter icon)
* Recent list now only include files that exists

**Comment by rodlie** [comment]
Also added "Clear Recent Files" in the edit menu.

Thanks for the feedback :+1:
