### ISSUE TITLE
Delete shortcut doesn't seem to be working

### ISSUE THREAD

**Issue by stibinator** [friction2d/friction#149]
I can't delete things using the delete key (I tried backspace as well, but no dice).

Version: Friction 0.9.5 / Arch linux / X11
Steps to reproduce: 
 - Create an object in the scene
 - Hit `delete` key on keyboard

Expected: object is deleted
Observed: nothing happens

**Comment by stibinator** [comment]
Oh, ok, it's impossible to delete objects if any tool other than the select tool is active. This isn't very intuitive.

**Comment by stibinator** [comment]
Might want to look at the UX for this.

**Comment by rodlie** [comment]
Why? Delete works as intended.

If you are in point mode you don't want delete your object when you mark one point etc.
