### ISSUE TITLE
Adding gradient is  undiscovarable

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#154]
you need to right clcik  in to list of gradeints that does not  very discoverable.
It would be nice if gradeit would be created automatically after you switch to that checkbox . or/and add button as a list item with + label and add gradeint

**Comment by rodlie** [comment]
A button could be added. Not sure I want to automatically add a gradient (I see several potential issues with that approach).

Suggestions are of course welcome :)

**Comment by adambelis** [comment]
I know you probably use gradeints as definitions /swaches . there are two solutions
just bite the bullet and have lots of gradients in definitions (usually not that big of the deal if you'd design around it : have command that  merges all same gradeints if needed)

second is that create gradeint only if there is no gradeint in document. i would lean to solution 1

this dialog could should be copletyl redesign but i can open separate  issue for that if you are interested in  redesing
![image](https://github.com/friction2d/friction/assets/50795097/6cc07eb4-f02d-4677-b5c7-bdec22ff9120)

something like we did in inksape would be nice
![image](https://github.com/friction2d/friction/assets/50795097/002dc6db-ec68-44e6-a015-0ae4eb1ecc56)

**Comment by rodlie** [comment]
Thanks for the suggestions. I will look into this issue when I get the time, maybe this weekend.

A potential redesign is not planned at the moment, I would rather get what we have stable and usable than introduce new stuff, but I'm open for changes after v1.

**Comment by adambelis** [comment]
Yes my suggestions are more of the Sid of ux.  From what I tested so far did not have any crash yet .  Mostly.just ux bugs. But will need to try Veet som more complex project and see

**Comment by rodlie** [comment]
I would say it relativity stable (if you stay away from too many shader effects and don't go crazy with expressions on everything), I use Friction at work (the reason this project exists) on many different projects almost daily, and I fix issues as they pop up on our end and the workflow is mostly based on our needs/quirks at work.

**Comment by adambelis** [comment]
I am really glad that you picked it up I was bummed when enve 2d stoped development.  I will try to add. More suggestions report more stuff if I get time

**Comment by rodlie** [comment]
> More suggestions report more stuff if I get time

Great :+1:

**Comment by rodlie** [comment]
A new gradient will now be added if none exists if you click 'gradient'.

I also added three buttons (add/remove/duplicate):
![friction-fillstroke-gradient](https://github.com/friction2d/friction/assets/34516798/cfe5354b-dfaf-43ae-9828-8306236599a3)

They do waste a bit of space, unsure ...

**Comment by rodlie** [comment]
New version:
![friction-fillstroke-gradv2](https://github.com/friction2d/friction/assets/34516798/d1c8392c-fbb0-4a80-9e26-accdd5e4b0f0)
