### ISSUE TITLE
Playback cache issues on Mac

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#16]
The cache is not invalidated after simple changes (show/hide object) on Mac. Works on Linux.

**Comment by MaurycyLiebner** [comment]
It may something to do with invalid total and available memory estimation for Mac. Both were not tested at all since I do not own an Apple PC.
See **src/app/hardwareinfo.cpp** and **src/app/memorychecker.cpp**

**Comment by rodlie** [comment]
will check this weekend, thanks for the feedback 👍 

The memory total should be correct, available I don't know.

**Comment by rodlie** [comment]
btw, if you have any issues with me forking let me know, I can also change the name even more if wanted. Or merge back changes. Up to you :)

**Comment by rodlie** [comment]
I have decided to drop support for macOS.

Currently it's a waste of my time, the issues seems to be primarily in tcmalloc. Will focus on Linux, and maybe try to get Windows working (a big maybe).
