### ISSUE TITLE
Do not stop  preview while tweaking  keyframes on timline  /graph

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#161]
Curently  playbec stops every time you change keyfram  this is quit annoying while tweaking timing  of animaitons
https://github.com/friction2d/friction/assets/50795097/68e1f92c-901f-4c62-9f18-38bfcd48f6d6

its probably performance problem but i would still prefer if i hade to wayt for recalculation then nonstop hitting space bar 

https://github.com/friction2d/friction/assets/50795097/adb5f5be-e008-4445-9797-b6b76d98fa75

**Comment by rodlie** [comment]
Currently the playback will stop if you change anything, no point in looking at old cache. This was a workaround for something at some point, don't remember.

I see no reason why we can't re-cache when something change (during playback).

**Comment by adambelis** [comment]
btw imho OBS has very nice theme if you alos want to try that as a base https://obsproject.com/forum/resources/yami-resized.1611/updates

**Comment by rodlie** [comment]
Fixed in https://github.com/friction2d/friction/commit/ec431c77862a82f1752946d59e7054fbf181aa08

https://github.com/friction2d/friction/assets/34516798/c8251e2f-84fb-4442-bbeb-deea8f73e11a
