### ISSUE TITLE
Selected keys in Graph - low contrast

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#163]
Its currently hard to see which keys are selected and which are not.
  - gray+ bg outline for nonslected
  - blue +white for selected 
 
![image](https://github.com/friction2d/friction/assets/50795097/43469ffd-f46f-43f5-aecb-353ec243a03a)

also, colors for lines x and y could be tweaked to be less aggressive overcontrasty

#3f9af5
#f53f41

**Comment by adambelis** [comment]
since curretn ui uses  red for selecion that is also an option to use bu i like blue better 
![image](https://github.com/friction2d/friction/assets/50795097/9e2fe0df-1537-4078-bffe-d18ce1420102)

**Comment by rodlie** [comment]
#155

**Comment by rodlie** [comment]
Current implementation *(not identical, but better than it was)*:

![Screenshot from 2024-07-21 15-49-13](https://github.com/user-attachments/assets/57bb9800-ce62-415a-8f9c-577ff382e130)
![Screenshot from 2024-07-21 15-49-36](https://github.com/user-attachments/assets/f75ee078-3c83-42d0-9577-86345a2eaf4c)
![Screenshot from 2024-07-21 15-49-54](https://github.com/user-attachments/assets/011734af-4fcb-43d5-ba81-383337c7d542)

**Comment by rodlie** [comment]
Did some minor improvements:

https://github.com/user-attachments/assets/0f50b107-f34c-41f4-a619-169da45754f6
