### ISSUE TITLE
"paths" animation SVG export

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#165]
i did simple animation  with path in 0.9.6b . Export to SVG seems to be broken .
![friction_mLr92QVkZ8](https://github.com/friction2d/friction/assets/50795097/162827d9-34de-4a6f-9d54-2a761602fe63)

render works fine 
https://github.com/friction2d/friction/assets/50795097/8e343320-357d-4715-99a2-5e0897c9cfa9

svg 
![animation test export](https://github.com/friction2d/friction/assets/50795097/be445ad0-c838-45fe-9593-feb10503f7e1)

Frion file
[animation text.zip](https://github.com/friction2d/friction/files/15443481/animation.text.zip)

**Comment by rodlie** [comment]
Seems like the Path object "paths" keyframes are exported incorrectly(?). It's probably something missing/wrong in the XML (looks ok to me, but I'm no SVG spec wizard).

**Comment by adambelis** [comment]
hmm yes  i found an example of working svg it has different formating (maybe both valid )
https://codepen.io/AnnieChn/pen/JEQXyB

**Comment by adambelis** [comment]
OK chat gpt  know what is wrong (actually i am very impressed :D)
https://chatgpt.com/share/c7d63c57-8431-4d30-80b8-45711d153ca9

**Comment by adambelis** [comment]
![animation test export- caht pgt fix](https://github.com/friction2d/friction/assets/50795097/8aceb31e-7e6b-43b4-92cd-debfa59a4ef7)

fixed by chat gpt

**Comment by rodlie** [comment]
Nice :+1: 

Now I need to figure out where this problem happens in the code ..... meeeeh :)

**Comment by rodlie** [comment]
The real issue was

> Each time value in the keyTimes list is specified as a floating point value between 0 and 1 (inclusive)

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keyTimes

So, we strip `-` from any keyTimes (not convert) when exporting and check if parent (`path`) has `d`, if not then we add `d="M0 0"`, I'm now able to export a functional SVG from your project file.

I need to test this a bit more before I commit, don't want to break anything.

**Comment by adambelis** [comment]
conforming fix
