### ISSUE TITLE
Disabled states in context menu do not look disabled

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#168]
![image](https://github.com/friction2d/friction/assets/50795097/e800cdc0-bc22-4143-9592-08d5a3d926ad)

**Comment by rodlie** [comment]
Fixed in https://github.com/friction2d/friction/commit/bbe85eece0cf854eb5fb33f62b2fd2b74c5dab05
![friction-qmenu-disabled-state](https://github.com/friction2d/friction/assets/34516798/cd5f3b29-8c2d-457e-b146-358a2029828e)
