### ISSUE TITLE
Deleting object does not delete keyframes in Graph

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#176]
1. Open Fricion and create a rectangle
2. add animation keyframes to any properties
3. enable visibility  in graph
4.  delete object
5.  switch to graph

keyframes are still there

https://github.com/friction2d/friction/assets/50795097/fa9c26a9-aa75-48d4-93b2-fefd049409d0

keyframe should be deleted with the object

**Comment by rodlie** [comment]
Thanks for detecting this issue.

At the code level graph animators are removed when the object is destroyed. Either the object is not actually destroyed or the destroy signal is never emitted.

**Comment by adambelis** [comment]
looks good to me (don't listen to me on code advice :D).  If you push out build i will test

**Comment by rodlie** [comment]
Just brainstorming, it's also more about logic than code :)

Will try to push out a build later tonight, currently at work.

**Comment by adambelis** [comment]
it sounds like logical solution
