### ISSUE TITLE
Tools do not have shorcuts.

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#182]
We could add shorcuts for tools we could follow  Inkscpae
S - Select  (probably problematic in selection tool since it fight scale function )
B - bezier pen
N - node tool
R - Rectangle (probably problematic in selection tool since it fight rotation function )
E - Eli[see
X ? - Null
D - dropper tool  

Or illustrator / after effects

V - selection tool
A - Node tool
P - Bezier pen
M - rectangle
L -Elipse
x? - null
I -eye droper

**Comment by rodlie** [comment]
I prefer what we have now (function keys), but open for suggestions.

**Comment by rodlie** [comment]
btw, forgot to say that you can change the shortcuts for the tools, it's just not documented nor have a UI (or check if the shortcut is already in use, or supported).

In `friction.conf` (in Windows this is sadly the register):
```
[shortcuts]
boxTransform=F1
pointTransform=F2
pathCreate=F3
drawPath=F4
circleMode=F5
rectMode=F6
textMode=F7
nullMode=F8
pickMode=F9
```

**Comment by adambelis** [comment]
ah i didnt know thta since this is not in shortcuts  dialog.
I this think that human readable shortcuts would be nice if they are free but not necsery

**Comment by rodlie** [comment]
>not in shortcuts dialog

My bad, should be in the dialog, probably just forgot. Will add.

**Comment by Beryesa** [comment]
I'd highly suggest using a default shortcut for "Add keys" as well
Since it's blender-esque, further inspirations would be, welcome?

**Comment by rodlie** [comment]
I'm open for suggestions on any (new) shortcuts. Just name the action and shortcut and we will figure out something.

In the long run we need a shortcut manager, but that's for v1.1+

**Comment by rodlie** [comment]
> I'd highly suggest using a default shortcut for "Add keys" as well

Done, shortcut is `Insert`.

Will close this, most actions has a shortcut and we now have a command palette.

A shortcut editor will happen sometime after v1.0.

**Comment by Beryesa** [comment]
I would suggest "i" like Blender (just like the g r s) but this is also nice, looking forward to the shortcut editor, thanks!

**Comment by rodlie** [comment]
`I` is reserved for frame In.
