### ISSUE TITLE
Defoult style for objects

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#183]
This is titaly subjective but i think defoult style for objects / fusia outline with 2 px is kind of ugly

 i suggest #ff0066ff 10px width
 
 
![image](https://github.com/friction2d/friction/assets/50795097/fedbd390-9448-4042-9a9a-e7792deb61d7)

**Comment by rodlie** [comment]
Sure.

#155

**Comment by rodlie** [comment]
Fixed in https://github.com/friction2d/friction/commit/65502ae18e63a704ba029d42158f6d5c47def9c2
