### ISSUE TITLE
SVG import does not support <line>

### ISSUE THREAD

**Issue by vestineo** [friction2d/friction#188]
`<line>` tag from SVG file get ignored.
I have attached screenshot from Inkscape and frcition to show the difference.

**Friction**
![Screenshot 2024-06-13 220902](https://github.com/friction2d/friction/assets/8676441/f0e7e3c2-bfff-46a0-a894-2dc428354417)

**Inkscape**
![image](https://github.com/friction2d/friction/assets/8676441/643a8b16-58e3-402d-b44e-9922184bc62b)

SVG File
![line](https://github.com/friction2d/friction/assets/8676441/afc4fc67-8eaa-4e8a-acdf-3379c0efdaa0)

**Comment by vestineo** [comment]
I have made changes to `svgimporter` to support line tag. I would love to contribute to the project and create a pull request.

![Screenshot 2024-06-13 225042](https://github.com/friction2d/friction/assets/8676441/bc3ad83a-5c04-4a37-8dbb-c62e14a2985f)

**Comment by rodlie** [comment]
> I have made changes to svgimporter to support line tag. I would love to contribute to the project and create a pull request.

Sure, any issue with a fix is always welcome :+1:

**Comment by rodlie** [comment]
Note: the default repository when doing PR is enve, remember to switch to friction2d/friction/main.
