### ISSUE TITLE
Moving floating Timeline window back to Main Window

### ISSUE THREAD

**Issue by doc-halo** [friction2d/friction#196]
I cannot get the floating Timeline window back to become part of the Main Window. See screenshot below.

![image](https://github.com/friction2d/friction/assets/10502218/de4878af-7f99-43a4-99af-ba0fb48dd457)

I would like the floating Timeline window to go back to it's original place under the Scene window. And not remain floating.

I'm running 0.9.6 on both windows and zorinos and for both I'm experiencing the same issue.

Thanks

**Comment by rodlie** [comment]
View=>Timeline Window

**Comment by doc-halo** [comment]
Unfortunately, this doesn't work. It will just pop-up again as a floating window.

**Comment by rodlie** [comment]
https://github.com/friction2d/friction/assets/34516798/84d155ca-e271-43ba-80e4-22979eea40dd

**Comment by doc-halo** [comment]
Ok. That worked. Thank you for your timely help.
