### ISSUE TITLE
SVG stroke-linecap & stroke-linejoin not supported

### ISSUE THREAD

**Issue by vestineo** [friction2d/friction#197]
`stroke-linecap` and `stroke-linejoin` are not supported while importing SVG file. They fallback to default `round` for both linejoin and linecap.
Also, default values (when join and cap style not specified) are different according to SVG specifications. Default values for linejoin should be `miter` and for linecap that should be `butt`.

https://www.w3.org/TR/2002/CR-SVG11-20020430/painting.html#StrokeProperties

Screenshot
![Screenshot 2024-06-30 204133](https://github.com/friction2d/friction/assets/8676441/265497ea-d7f8-4d3b-aa9d-78b3b9585a2b)

SVG Files
![linecap_test](https://github.com/friction2d/friction/assets/8676441/77d897a8-6622-41e4-93b7-81f941912f60)
![linejoin_test](https://github.com/friction2d/friction/assets/8676441/50dec3da-8daf-4f3f-a472-d8225150064e)

**Comment by rodlie** [comment]
Looks good here:
![friction-spiderman](https://github.com/friction2d/friction/assets/34516798/ce30da91-2c16-459e-a140-086a8748ae44)

I will probably cherry-pick the fix for the v0.9 branch (0.9.6.1) since v1 will probably take a while.

**Comment by irwant** [comment]
also make it support for exporter
