### ISSUE TITLE
Scene actions visibility

### ISSUE THREAD

**Issue by Pebor** [friction2d/friction#205]
This might be a skill issue and imaturity in motion animation space.
But when I create a project, I don't usually have a render size target.
This results in me creating a scene with a default preset, changing stuff on the fly to meet my needs - in this project for example
![image](https://github.com/friction2d/friction/assets/32438954/9cd113f1-ef8b-4707-811c-4438bb534bc8)
I have added all the different shapes and my rectangle wont fit the 16:9 ratio if I just scaled up,
An option to resize the output view/scene view (which I haven't yet found) would be really helpful for more "fun" animations

**Comment by vestineo** [comment]
You can set the scene size when you initially create the project. You can also change that later on by right-click > settings.

https://github.com/friction2d/friction/assets/8676441/91adf6d5-c41d-4d01-9642-69d362403586

**Comment by Pebor** [comment]
It was a skill issue then, my bad!
One thing I wanna add though, maybe the scene options would make a bit more sense in the top bar? :thinking: 
![image](https://github.com/friction2d/friction/assets/32438954/e7b37c56-2a9d-456a-98cf-d1bcece01c41)
I kept initially looking up there for "project settings" or "Scene" and looking through preferences etc, because that's where these kind of options usually are in like inkscape.

**Comment by rodlie** [comment]
> maybe the scene options would make a bit more sense in the top bar?

It was moved to the toolbar (the "scene" option) for easier access (IMHO).

**Comment by Pebor** [comment]
Oh, that seems fair, but also, even though there is an option inside to "create new scene" that's what I thought until now that that's what it does. 
Every action on the toolbar creates or adds something, while the scene opens the scene settings?
Most probably because I don't have titles on, but this is the same thing you see when creating a new scene, so it really isn't clear that you're just editing the active one (minus the scene name)
![image](https://github.com/friction2d/friction/assets/32438954/4113a84a-3b89-46ac-b3ee-afc06dc6ee34)

**Comment by rodlie** [comment]
UX suggestions are welcome ;)

Clicking 'scene' in the toolbar will edit your current scene, I could of course rename it to something like 'scene properties', but it's a bit too long(?).

**Comment by Pebor** [comment]
I think the maybe simplest change would be to put everything from the right-click menu (in viewport) to the "scene" in toolbar, but changing the the dafult action (and probably icon) to new scene.

Alternatively, moving right-click into the top-bar, and having a shortcut to open scene properties?

Either way, the right-click menu is a bit weird when it's the only place "settings" for the scene is actually labeled.
Keeping the right-click menu and adding that same to the top bar would I think also would make sense, it's a duplicate, sure, but top bar is the standard to find all/important functionality while the right-click seems like a "neat trick".

Or *maybe* just changing the icon on the tool bar to have an edit wrench would make it more obvious, what that button does. :sweat_smile:

**Comment by rodlie** [comment]
> simplest change would be to put everything from the right-click menu (in viewport)

The right-click menu needs some work, I agree. This will be improved for the next feature version.

> Alternatively, moving right-click into the top-bar, and having a shortcut to open scene properties?

Adding them back is no biggie. The actions in the toolbar will be selectable/optional in a future release anyway, so a permanent location in the top menu makes sense.

> Or maybe just changing the icon on the tool bar to have an edit wrench would make it more obvious, what that button does

Not sure about that one, I like that the icons reflect the action (without reading the text), a 'wrench' icons does not say 'scene', it could be anything.

**Comment by rodlie** [comment]
> I didn't mean it to only be the wrench, but for the wrench to be on the scene icon.

Ah, then we agree :+1:

**Comment by Pebor** [comment]
Great! Thank you :smile: 
This fixes it everything for me, should I close the issue?

**Comment by rodlie** [comment]
> should I close the issue?

Not needed.
