### ISSUE TITLE
Undo stops working after importing svg

### ISSUE THREAD

**Issue by adambelis** [friction2d/friction#209]
1. open file
2. import any svg
3.  draw  new shape with pen tool
4. try to undo

nothing

**Comment by rodlie** [comment]
Known issue, for some reason loading some SVG's ends up in an invalid state that breaks undo.

Been a while since I experienced the issue and unable to replicate with random SVG's I have on hand, do you have a SVG you can share?

**Comment by adambelis** [comment]
![asdas](https://github.com/user-attachments/assets/c8ea982f-d790-4f45-9b5a-c59fcf9fcfd3)

**Comment by rodlie** [comment]
Hmm, could this be a Windows issue?

Works here with 0.9.6 and main:
![friction-svg-undo-state](https://github.com/user-attachments/assets/45a5a9b9-0d9a-4d1b-86db-1e7edfbac6c9)

Will test on Windows.

**Comment by adambelis** [comment]
Could be .

**Comment by rodlie** [comment]
Confirmed on Windows 11 using Friction 0.9.6.

So, it's a Windows issue. Explains why I have not been able to replicate it.

Workaround: after importing SVG save project and close/open.

Seems like something during import breaks the undo state (probably a signal or something that is not triggered on Windows), will need to debug this on Windows (meeeeeh).

**Comment by rodlie** [comment]
So, this is actually an issue with any import on Windows.

Have a fix, just need to test for any regressions.

**Comment by rodlie** [comment]
Test build: https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-8df58d7b/

**Comment by adambelis** [comment]
hmm this build does not seesm to fix the issue

**Comment by rodlie** [comment]
Works here, tested on Windows 10 and 11.

**Comment by rodlie** [comment]
Video from my Windows 11 laptop:

## 0.9.6

https://github.com/user-attachments/assets/912c1ec8-f5de-47df-90f6-5d4254fd103f

## 0.9.6.1-8df58d7b


https://github.com/user-attachments/assets/b3aa653b-f510-42da-93a4-10576dfebd31

**Comment by rodlie** [comment]
I consider this fixed and will close.
