### ISSUE TITLE
Bundle SVG Optimizer?

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#213]
Exported SVG's are not optimized and we have a lot of redundant groups etc that "bloat" the SVG.

https://github.com/friction2d/friction2d.github.io/blob/main/documentation/export.md#post-export

After testing all the optimizers I could find I ended up with SVGO, the only tool that actually collapsed the groups properly and didn't break the SVG.

Sadly I can't find any libraries that can help me integrate such a feature in Friction and SVGO is node.js or cli.

My proposal is to bundle SVGO binaries (or at least support it) with Friction, if binary found have a checkbox on export called optimize or something and in the background just run the tool.

The downside is the size, SVGO bin's are ~40MB.

**Comment by rodlie** [comment]
Added repo https://github.com/friction2d/friction-svgo, it will produce binaries (only tested on Linux) of SVGO.

**Comment by irwant** [comment]
I think that no need to bundling SVGO application to the Friction binaries. 
Think to using extension like Inkscape

**Comment by rodlie** [comment]
I would prefer to have SVGO available in Friction, when I do exports I want to have the option to export optimized (for use on the web), I assume most users would prefer that(?).

![Screenshot from 2024-08-20 12-47-13](https://github.com/user-attachments/assets/9bf0362a-8721-41f1-9edf-c324a0607e32)

*In a perfect world this would be part of the Friction code, but I don't have time or the motivation to make a SVG parser when something that works exists.*

> Think to using extension like Inkscape

Maybe, but that will require a lot of additional work just for one feature (at this time). In the future we could add "extension" options for svg export if needed.

This is my opinion of course, I'm open for discussion.

**Comment by rodlie** [comment]
Ok, so my current suggestion for Windows portable is to have a separate 7z file called `friction-svgo-windows-x64.7z` that includes the `svgo-win.exe` binary required to run the SVG optimizer on export, just put the file in the friction portable folder and "it just works".

For the installer you will have the option to install the optimizer(?).

Are we ok on Windows?

![Screenshot from 2024-08-23 12-42-57](https://github.com/user-attachments/assets/6584690c-a2ec-4d97-b9f1-8fc011f9f624)
![Screenshot from 2024-08-23 12-43-08](https://github.com/user-attachments/assets/0af3ab95-d753-4204-939e-4790698807aa)

**Comment by rodlie** [comment]
The Windows installer will look like this:
![friction-win-installer](https://github.com/user-attachments/assets/23186485-c652-49d8-bdf5-688ecadc6593)
