### ISSUE TITLE
disconnect node path not working.

### ISSUE THREAD

**Issue by irwant** [friction2d/friction#218]
this is a bug, disconnect node path not working.

**Comment by rodlie** [comment]
Works for me.

**Comment by irwant** [comment]
yes, that working, with select two node. I am sorry, i think to disconnect node just select one node like on inkscape

**Comment by rodlie** [comment]
'Disconnect Nodes' in Friction would be equal to 'Delete segment between two non-end nodes' in Inkscape if I'm not mistaken.
