### ISSUE TITLE
Two small errors when exporting

### ISSUE THREAD

**Issue by eFe-Munoz** [friction2d/friction#219]
Hello, I am looking forward to the release of Friction 1.0.

here are two small bugs maintained from Enve that I would like to comment.

When I export for example animated titles to edit in other video editing programs, the most comfortable format is to export a sequence of images in “png” format (especially because it supports transparencies). If I select  “image2sequence” in png, the default codec is png24 and not rgba (rgb + alpha). If an average user does not know how to change it, he will not be able to export a png with transparencies.

The second small error is that even selecting png as format the sequence is exported in bmp, since the text that seems automatic is: sequence_%05d.bmp .

Best regards!

**Comment by rodlie** [comment]
> When you export for example animated titles to edit in other video editing programs, the most comfortable format is to export a sequence of images in “png” format (especially because it supports transparencies). When you section “image2sequence” in png, the default codec is png24 and not rgba (rgb + alpha). If an average user does not know how to change it, he will not be able to get a png with transparencies.

Sure, I can do something about this.

Personally I use ProRes when exporting stuff for use in other apps.

For v1 I want to document "how to export" for various use cases.

> The second small error is that even selecting png as format the sequence is exported in bmp, since the text that seems automatic is: sequence_%05d.bmp .

I know about this one, it has always been a minor annoyance *(but not enough to do anything about)*. Will fix.

---

Will try to get this fixed for 0.9.6.1 (and v1 of course).

**Comment by rodlie** [comment]
> > When you export for example animated titles to edit in other video editing programs, the most comfortable format is to export a sequence of images in “png” format (especially because it supports transparencies). When you section “image2sequence” in png, the default codec is png24 and not rgba (rgb + alpha). If an average user does not know how to change it, he will not be able to get a png with transparencies.
> 
> Sure, I can do something about this.

This will require a lot of work, Friction does not know anything about pixel formats for export, it just list available options from FFmpeg, whatever is the first option from FFmpeg will be the selected option in the combo box.

I think we should have a small collection of "good" presets included with Friction, and output settings should be considered "advanced". With documentation I think this could be the best solution(?).

**Comment by eFe-Munoz** [comment]
I agree that there should be basic presets for export. That would help newbies a lot. Prorres, mp4, png....

**Comment by rodlie** [comment]
The image sequence file extension issue has been fixed in v1, will backport to v0.9 also.

**Comment by rodlie** [comment]
Will close this, the preset discussion has moved to #220
