### ISSUE TITLE
Default set of export presets

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#220]
As discussed in #219 with @eFe-Munoz we should have a default set of export presets ready to go in Friction.

What are the most common export format and settings we should use?

Suggestion:

* h264
* h264 (baseline)
* h265 (HEVC)
* ProRes 422
* ProRes 444
* ProRes 444 Alpha
* WebM (VP8)
* WebM (VP9)
* PNG image sequence
* TIFF image sequence

That should cover the basics?

Also need separate presets for audio options, like

* h264 + MP3
* ProRes + AAC
* WebM + Vorbis

or something? I don't know, we need to agree on a set of video and audio codecs + quality.

Keep it simple, this is just starter presets.

**Comment by eFe-Munoz** [comment]
I would simplify to the 3 or 4 most used formats:

- mp4 (h264)
- Prores 444
- png sequence
- TIFF sequence

The rest already seem to me to be advanced options for professionals that could go in the options.

**Comment by rodlie** [comment]
We also need to consider audio and quality (for video).

And if you target video on the web (on a website) then h264 (baseline) and WebM (VP8) are your target formats (for best compatibility).

For intermediate formats, for use in other apps or as a "master", then ProRes 444, TIFF and PNG is a requirement.

For "social media" then MP4 (h264+mp3 if sound) does the job.

But, yeah... we should keep it simple :smile:

**Comment by rodlie** [comment]
And how is this going to work?

1. Should Friction search for an additional path for bundle presets?
2. What if the users don't want them, they might not be uninstallable depending on how you installed Friction
3. Should Friction create them on first startup and put them in the user dir? What is a first startup?

**Comment by eFe-Munoz** [comment]
You are right about the formats.

Regarding how to present it, you could show some basic ones and on the other hand an advanced button. Likewise, when selecting a preset, you can see its characteristics to modify it.

If it would allow you to save your own presets it would be great.

**Comment by eFe-Munoz** [comment]
For example, Premiere displays the format and quality preset.

Then further down it allows you to modify advanced video and audio settings.

![imagen](https://github.com/user-attachments/assets/793430ca-36f1-48fb-bce6-33cad7582cfd)

**Comment by rodlie** [comment]
> Regarding how to present it

The current render UI need a lot of work, there will probably not be too many changes until after v1.0. Depends on the amount of work needed.

I would also prefer a kind of "quick export" button in the main toolbar (use the 'render' button we have today), where you get a popup/dialog, select a preset and done.

> For example, Premiere displays the format and quality preset

Seems like a good solution.

---

> And how is this going to work?
> 
> 1. Should Friction search for an additional path for bundle presets?
> 2. What if the users don't want them, they might not be removable depending on how you installed Friction
> 3. Should Friction create them on first startup and put them in the user dir? What is a first startup?

Answering myself :P

I think option 3 would be best and have a value in the settings if the user have used this feature before (so we don't add them again).

**Comment by rodlie** [comment]
Suggestion v2:

- MP4 Video
- MP4 Video + Audio
- ProRes Video
- ProRes Video + Audio
- PNG Image(s)
- TIFF Image(s)
---
* MP4 is h264 default (+ audio is MP3 320kbps)
* ProRes is 444 Alpha (+ audio is AAC 320kbps)
* Both PNG and TIFF has alpha enabled

**Comment by eFe-Munoz** [comment]
I Vote in favor

**Comment by rodlie** [comment]
Feature implemented with suggestion v2.

I can backport this to 0.9.6.1 if wanted? (I have no ETA on v1 stable)

**Comment by eFe-Munoz** [comment]
Great if you do, I can test it

**Comment by rodlie** [comment]
When I think about it, we should just call it 0.9.7. 0.9.6.1 was reserved for critical fixes only and we include more than that already.

**Comment by eFe-Munoz** [comment]
Ok

**Comment by rodlie** [comment]
Windows test build: https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-b2c6df28/

Changes since v0.9.6: https://github.com/friction2d/friction2d.github.io/blob/main/_drafts/friction-0961.md#changes

**Comment by rodlie** [comment]
Works on my systems.

I assume by first startup window you mean the terminal? What is the last line before it closes?

**Comment by eFe-Munoz** [comment]
I have started the program as administrator and it starts fine. 

In export I see no changes... when I select “image2seequence” in png it still shows png24 instead of rgba.

**Comment by rodlie** [comment]
> I have started the program as administrator and it starts fine.

And regular 0.9.6 works fine as a user? But not 0.9.6.1?

> In export I see no changes... when I select “image2seequence” in png it still shows png24 instead of rgba.

The point of this issue was to introduce a set of presets so you don't have to go to the "advanced" settings, they will not be changed as I said in issue #219

**Comment by eFe-Munoz** [comment]
I can´t find the presets... Where are?

**Comment by rodlie** [comment]
> I can´t find the presets... Where are?
![presets](https://github.com/user-attachments/assets/89b41e01-334c-4e39-b467-d50cf85a7a46)

**Comment by eFe-Munoz** [comment]
Maybe if instead of “...” it says “presets”.

**Comment by rodlie** [comment]
> Oh, I guess it's not a very intuitive site. can the presets come up when you press output? If you don't know it, I think it might be difficult to find them.

> Maybe if instead of “...” it says “presets”.

Sure, we can do something about that.

But, I'm more concerned about the startup/crash issue, this has to be resolved, but I'm not able to replicate.

**Comment by eFe-Munoz** [comment]
When I started the program as administrator it worked fine.

**Comment by rodlie** [comment]
That is not a solution or a workaround. Something is wrong.

**Comment by eFe-Munoz** [comment]
I think it's just a permissions problem. It is a portable executable. That's why it needs permissions. If it were installed I don't think there would be a problem.

**Comment by rodlie** [comment]
Unsure, I will produce a couple of new builds for you to test. Will let you know when they are ready.

**Comment by rodlie** [comment]
https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-tests/friction-0.9.6.1-3fd83da4-windows-x64.7z/download

This build should notify if there are any permission issues.

**Comment by rodlie** [comment]
> > Oh, I guess it's not a very intuitive site. can the presets come up when you press output? If you don't know it, I think it might be difficult to find them.
> 
> > Maybe if instead of “...” it says “presets”.
> 
> Sure, we can do something about that.

How it currently looks in v1 *(I will not do any more UI changes in v0.9)*:
![Screenshot from 2024-08-16 00-31-24](https://github.com/user-attachments/assets/b8eeee84-11db-4b04-a449-4a78252f1e00)

**Comment by eFe-Munoz** [comment]
looks great!

**Comment by rodlie** [comment]
> https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-tests/friction-0.9.6.1-3fd83da4-windows-x64.7z/download
> 
> This build should notify if there are any permission issues.
> 
> **Run as user**

@eFe-Munoz Did you test this build as a user? Did it start (or give you a dialog regarding permission issue)? and does regular 0.9.6 start when run as user?

**Comment by eFe-Munoz** [comment]
When starting it as a user, it hangs in the console window, like the previous vers

![imagen](https://github.com/user-attachments/assets/c5967774-df27-489e-bfe5-6fd92e1b5cc3)

**Comment by rodlie** [comment]
Thanks for the info, this also applies to 0.9.6?

Interesting. It stops on GPU setup, very odd. It's waiting for something related to the GPU.

**Comment by eFe-Munoz** [comment]
I have an Nvidia RTX 3060.

In Administrator mode it opens fine.

Friction 9.6 (installed) does open fine without administrator permissions.

**Comment by rodlie** [comment]
Thanks.

Could you try one more thing, test the 0.9.6 portable: https://github.com/friction2d/friction/releases/download/v0.9.6/friction-0.9.6-portable-windows-x64.7z

I want to check if this is an issue introduced with 0.9.6.1 or an unrelated (Windows) issue.

**Comment by eFe-Munoz** [comment]
9.6 portable opens well!

**Comment by rodlie** [comment]
not good... In regards to 0.9.6.1 release.

Ok, I did a snapshot release after I fixed the undo issue a while back, does that run normal? https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-8df58d7b/friction-0.9.6.1-8df58d7b-portable-windows-x64.7z/download

*Odd that I can't replicate this, I have three Windows (10 and 11) computers I test on, two NVIDIA and one Intel.*

**Comment by eFe-Munoz** [comment]
This version stop in the same place:
![imagen](https://github.com/user-attachments/assets/38694464-a9c0-4057-9643-627774e5d829)

**Comment by rodlie** [comment]
> This version stop in the same place

Thanks again, that version is almost identical to 0.9.6.

> I think it's just a permissions problem. It is a portable executable. That's why it needs permissions. If it were installed I don't think there would be a problem.

I'm starting to think you are correct, probably related to the app not being signed or "verified". The regular 0.9.6 has been around for a while and has a "good" score or something, I don't know :smile:

**Comment by eFe-Munoz** [comment]
It is quite possible

**Comment by rodlie** [comment]
Sadly signing an application is expensive (the certificate costs money each year). This is one of the reasons I want Friction in the Microsoft Store (they sign and verify the app).

**Comment by eFe-Munoz** [comment]
That is very well thought out. But I wouldn't worry too much. It is common to run a program as administrator (especially portables).

**Comment by rodlie** [comment]
Ok, I will close this issue. The default presets works (tested on 5 computers), not the best UI in 0.9.6.x but will be improved in v1.0.
