### ISSUE TITLE
stroke-linecap and stroke-linejoin not exported on SVG

### ISSUE THREAD

**Issue by irwant** [friction2d/friction#223]
this sample properties not exported 
`stroke-linecap = "round"` value "round, butt, square"
`stroke-linejoin = "round"` value "round, miter, bevel"

**Comment by rodlie** [comment]
Test build: https://sourceforge.net/projects/friction/files/snapshots/0.9.6.1-cc1aa80a/

**Comment by irwant** [comment]
nice working
