### ISSUE TITLE
Release binaries discussion (v1.0.x)

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#225]
Hi all,

I would like to review the release binary selection in v1.0.x and moving forward.

Currently we offer a Windows installer (using inno) and a portable 7zip archive with the same content (only the package format differs). On Linux we offer a portable tar archive, AppImage and an RPM. The content is the same (only the package format differs).

As you can see there is a lot of duplication just to offer convenient options for the user.

## Windows

The two options we offer are the normal way (IMHO) to handle software on Windows, you get to pick between an installer and some kind of portable solution.

I'm currently not going to do any changes here unless I get user feedback that say otherwise. We will try out the Microsoft Store with v1.0 (if we get approved) and maybe do some changes based on our experiences with that solution. The con is that we need another package format on Windows... joy :smile: 

**Note:** In v1.0 the binaries will actually be portable, your settings etc are all contained in your Friction folder.

## Linux

Ah, yes ... The famous how to I distribute stuff on Linux.

I want to streamline this, I'm getting tired of maintaining various packaging solutions just to get questions on why I don't support additional package format X, Y or whatever. It will never be enough :smile: 

My current suggestion is to only keep the portable archive and if someone wants to maintain a flatpak let me know and we will make it official. But it **must** be a repack of the portable else no-go (that also means less work, just extract, move some files, done).

*What about the AppImage and RPM!???* Will you miss them? What do they offer vs. the portable?

**Note:** The portable in v1.0 is now true portable, your settings etc are located in the same folder as Friction and it offers XDG integration (desktop).

#### Pros

* One-click-run (if executable)

#### Cons

* Much larger than the portable (when compressed)
* Not true portable, settings etc are lost
* No XDG/freedesktop integration
* Might require additional software to work (fuse)

**Note:** I have nothing against AppImage.

### RPM

Well, the pros are easy, if you have a RPM system it might be more convenient to use that, or if you need to install/manage more systems.

I have not checked the stats for downloads so I don't know how many (if any) uses the RPM. If the stats show very low number I will remove it. Anyone against?

---

This is just my notes, feedback wanted.

**Comment by mokalux** [comment]
I am on windows 11 and using the portable version of friction is just fine with me 👍

**Comment by rodlie** [comment]
### "Fixing" AppImage

So, we will keep the AppImage, but I have done some modifications to fix the "problems" I have with AppImage's.

The AppImage will now support portable settings, if the folder where the AppImage is located is writable Friction will create a folder called `Friction-VERSION.AppImage.config` beside the AppImage, everything you do (related to config/presets) will be contained in that folder.

The AppImage will now support desktop integration, on first run you will be asked to integrate the AppImage, this can also be controlled with the commands: `--xdg-install` and `--xdg-remove`.

Now the only "issue" with the AppImage is the file size, but that's something I can live with.

```
-rw-r--r-- 1 root root  24M aug.  18 21:45 friction-1.0.0-65e1b021-linux-x86_64.tar.xz
-rwxr-xr-x 1 root root  31M aug.  18 21:45 Friction-1.0.0-65e1b021-x86_64.AppImage
```
