### ISSUE TITLE
Easing: add basic support

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#228]
So, this has already been done in branch `easing`, just forgot to make a issue.

> Easing has been traditionally restricted to the expression editor (includes a dedicated easing tab), requiring advanced user knowledge. We've simplified this by introducing user-friendly easing options in the timeline and graph. Simply select your keyframes and choose the desired easing option.

* https://floss.social/@friction/112995482618146670
* https://floss.social/@friction/112995718371606104

Easing actions will be available in the graph, timeline and command palette.

![easy1](https://github.com/user-attachments/assets/ed5b254a-5fe4-4c14-8a75-a62144702072)
![easy2](https://github.com/user-attachments/assets/34f0ca0e-1148-414b-9ad3-b7ece292b731)
![easy3](https://github.com/user-attachments/assets/a4984aaf-c6bb-4dee-8bb8-0db31acc394e)
![easy4](https://github.com/user-attachments/assets/2f9c8796-424a-4e87-892b-dc8eadf2d839)

**Comment by rodlie** [comment]
Merged into `main`.

**Comment by irwant** [comment]
How to make the keyframe back to the linear ? There are no way to back into linear except manual.

**Comment by rodlie** [comment]
Don't understand the question.

**Comment by rodlie** [comment]
Btw, there is a small undo bug with this feature, you will have to undo twice to go back. This is because the easing process requires two steps, one to calculate and one to apply, both steps are recorded in the undo.
