### ISSUE TITLE
Paste : Path with Gradient

### ISSUE THREAD

**Issue by irwant** [friction2d/friction#231]
Path with gradient copied from scene A not paste properly to scene B. the color fill changed to solid black color after pasted path with gradient.

**Comment by rodlie** [comment]
Confirmed, the gradient is not copied to the new scene.

**Comment by rodlie** [comment]
This one is tricky... The copied item(s) only reference the gradient and scene ID, when pasted to another scene we don't have a valid reference anymore, so no gradient.
