### ISSUE TITLE
Small proposals for improvements

### ISSUE THREAD

**Issue by eFe-Munoz** [friction2d/friction#233]
I think these are simple but helpful suggestions for the day-to-day work at Friction:

- When you press by mistake “New” instead of “File” it automatically creates a new file and you lose the work you were doing. This could be solved with a warning window that the job you are working on will be closed.

- To delete a file three steps are necessary: right click > Actions > Delete. When you have to delete multiple files it is very impractical, could they be deleted all at once with “Delete” or “Del”?

- And the last but of much use. To rename a file (very necessary in Friction not to get lost) two steps are necessary: right click > rename. It would be great if with a double click you could edit the file in place.

Thanks for the work done and best regards.

Fer.

**Comment by rodlie** [comment]
>When you press by mistake “New” instead of “File” it automatically creates a new file and you lose the work you were doing. This could be solved with a warning window that the job you are working on will be closed.

Sure.

> To delete a file three steps are necessary: right click > Actions > Delete. When you have to delete multiple files it is very impractical, could they be deleted all at once with “Delete” or “Del”?

I just use my `del` key, never used the menu, make sure your are in selection mode and the focus (red border) are on the timeline or viewer depending on where you are.

> And the last but of much use. To rename a file (very necessary in Friction not to get lost) two steps are necessary: right click > rename. It would be great if with a double click you could edit the file in place.

Currently in v1 double-click will expand/collapse the item, so unsure how to solve this.

**Comment by rodlie** [comment]
Will try to figure out a solution for the rename.

I just recently added double-click on layers to expand/collapse, as clicking on the small arrow to expand/collapse layers was very annoying.

**Comment by eFe-Munoz** [comment]
It is true

**Comment by eFe-Munoz** [comment]
Let's see what you think about this for renaming files. Do the same as the Windows operating system. One click leaves the object “selected” a second click renames (I think After Effects does this too).

And I would also put an associated key, so the user chooses one of the 2 methods.

**Comment by rodlie** [comment]
How about just using the middle button?

https://github.com/user-attachments/assets/8922cf2a-ac7e-48e7-9d20-f568b1c6c6cf
