### ISSUE TITLE
Minor feature request. Adding notification for exported SVG animation have done

### ISSUE THREAD

**Issue by irwant** [friction2d/friction#234]

**Comment by rodlie** [comment]
Sure, can add.

**Comment by rodlie** [comment]
![friction-export-svg-finished-dialog](https://github.com/user-attachments/assets/eb7ec691-0d53-4ffd-835a-a4eadd6591a4)
Ok?

**Comment by rodlie** [comment]
Also added an option to disable this feature if wanted.

![Screenshot from 2024-08-31 16-53-00](https://github.com/user-attachments/assets/6748ca71-596a-4d17-8cb3-1484b25e93d1)
