### ISSUE TITLE
Preset export png select bmp

### ISSUE THREAD

**Issue by eFe-Munoz** [friction2d/friction#238]
One small thing, when selecting the PNG FM export preset, the file it assigns is BMP (v.0.961-dev).

Best regards.
![imagen](https://github.com/user-attachments/assets/bb5a857d-1a8e-4085-9b61-38ee03b8b9b9)

**Comment by rodlie** [comment]
This was fixed in main and backported for 0.9.6.1 release several weeks ago, not able to replicate.
