### ISSUE TITLE
Black frame exporting png sequence

### ISSUE THREAD

**Issue by eFe-Munoz** [friction2d/friction#239]
Good morning, first of all I'm sorry for not putting all the posts in one, I upload them as they appear to me working (so I don't forget to upload them).

When you select the output png sequence with alpha, when exporting the sequence if in the first frame nothing appears (it is totally transparent) that frame appears all black (this happens from Enve). It is not serious because it can be deleted.

Best regards.

![imagen](https://github.com/user-attachments/assets/323b04a5-c944-487d-a3b1-b6a05fb5730c)

**Comment by rodlie** [comment]
Not able to replicate.
![Screenshot from 2024-09-02 11-48-04](https://github.com/user-attachments/assets/b9fa57d9-ad9e-40b6-ace4-5e9b93e23898)

![Screenshot from 2024-09-02 11-48-18](https://github.com/user-attachments/assets/811a01ad-6a77-4e36-9169-ddcf0435a6bb)

**Comment by eFe-Munoz** [comment]
Record the opacity of the “zero” object in the first frame, then record opacity 100 in another frame later.

This will result in the first frame being empty. If you export a png sequence, the first frame will be exported black.

**Comment by eFe-Munoz** [comment]
If there are several empty frames they will all be black.

**Comment by rodlie** [comment]
![Screenshot from 2024-09-02 11-58-15](https://github.com/user-attachments/assets/66ec4d55-0ea3-4aa2-9c19-9542cdb7a714)
![Screenshot from 2024-09-02 11-58-36](https://github.com/user-attachments/assets/a72d9f97-5bac-42f7-973d-752ec17d7422)
![Screenshot from 2024-09-02 11-58-57](https://github.com/user-attachments/assets/91fd95cb-6e88-456e-88d3-1c87ec30ddf2)

**Comment by eFe-Munoz** [comment]
Wow! I am on W10. This has always happened to me since ENVE.

**Comment by eFe-Munoz** [comment]
Can you share your example file?

**Comment by rodlie** [comment]
hmm, let me test on my W11 laptop after lunch.

**Comment by rodlie** [comment]
> Can you share your example file?

[fade-rotate.zip](https://github.com/user-attachments/files/16835915/fade-rotate.zip)

**Comment by eFe-Munoz** [comment]
With your file it also happens to me.

![imagen](https://github.com/user-attachments/assets/3db9d1c0-7824-407c-9145-4ee65babc98e)

**Comment by rodlie** [comment]
I can confirm that the preview in the Windows file manager is black on first frame, but the image is correct.

![Untitled-foo](https://github.com/user-attachments/assets/a511de39-985e-4cb2-8946-012a4e782e92)

untitled-00001.png:
![untitled-00001](https://github.com/user-attachments/assets/c4aaf423-9678-4eaf-9a58-e8d3b20d4074)
*As you can't see, it's transparent 😉*

**Comment by eFe-Munoz** [comment]
Great news!
