### ISSUE TITLE
AppImage (0.9.6.1) fails to run on Ubuntu 22.04 with execv error: No such file or directory

### ISSUE THREAD

**Issue by hsandt** [friction2d/friction#252]
**Repro**

Download AppImage on Ubuntu 22.04 and run it:

$ ./Friction-0.9.6.1-x86_64.AppImage 

See error:

> (AppImageLauncher:42849): GLib-CRITICAL **: 18:36:02.929: g_file_test: assertion 'filename != NULL' failed
execv error: No such file or directory

**Comment by rodlie** [comment]
Works fine here on 22.04.
