### ISSUE TITLE
Can't use accents in text

### ISSUE THREAD

**Issue by thiagochaves** [friction2d/friction#254]
I tried to add an accented letter to a text, but the text input ignores the accent. Accented letters in portuguese: á, é, í, ó, ú, â, ê, ô, ã. None of these can be input in the text field, although we can past these letters there.

**Comment by rodlie** [comment]
Confirmed, I'm so used to copy-paste that I didn't notice the issue. Thanks for the report :+1:

**Comment by rodlie** [comment]
Actually, no. On Linux it works, are you using Windows?

**Comment by rodlie** [comment]
It's the release builds it seems, my local build works fine. Probably something missing in Qt.

**Comment by rodlie** [comment]
For my reference: https://stackoverflow.com/questions/61444320/what-are-the-configure-options-for-qt-that-enable-dead-keys-usage

**Comment by thiagochaves** [comment]
Linux Mint 21, using the "Friction-0.9.6.1-x86_64.AppImage".

https://github.com/user-attachments/assets/0ba63e41-e48e-4167-ada5-e6a7c14f3b86

**Comment by rodlie** [comment]
Thanks.

I have identified the problem, it's with the included libxkbcommon library.

Workaround:

1. Extract the appimage: `./Friction-0.9.6.1-x86_64.AppImage --appimage-extract`
2. Remove libxkbcommon: `rm squashfs-root/usr/lib/libxkbcommon*`
3. Run from folder: `cd squashfs-root && ./AppRun`

**Comment by rodlie** [comment]
Fixed, snapshot available: https://sourceforge.net/projects/friction/files/snapshots/0.9.6.2-575020b2/

**Comment by thiagochaves** [comment]
Excellent, thanks a lot!

**Comment by nostradurus-beep** [comment]
I have a strange problem with special characters in the text šđčćžŠĐČĆŽ. When rendering everything is ok, but in SVG export they disappear and are replaced by some strange other character.
It doesn't matter if the character is present in the imported svg file or if it was entered manually. The font also doesn't matter although it is Arial/regular in the example below:
In editor: šđčćžŠĐČĆŽ
SVG output: �dcc���CC�
