### ISSUE TITLE
Help - Ability to clip objects

### ISSUE THREAD

**Issue by NusryNizam** [friction2d/friction#257]
Hi!

Is it possible to clip an image in Friction. So far, I've found nothing related to that. 
I have also tried bringing in SVGs from Inkscape that has linked and embedded images (clipped and not clipped), but it doesn't seem to recognize on Friction.

And seems like the only way is to import an image file directly. But I do not see any clipping option for objects or images. 

If its not on the roadmap, can we have it as a feature request?

Any help would be appreciated. Thanks for this awesome piece of software.

**Comment by rodlie** [comment]
Standard compositing functions are available.

Masking/Clipping can be done with SrcX/DstX modes on object/layers.

**Comment by NusryNizam** [comment]
That's helpful. Thank you!
