### ISSUE TITLE
Windows Defender is blocking the installation

### ISSUE THREAD

**Issue by yasharya2901** [friction2d/friction#260]
![image](https://github.com/user-attachments/assets/9d143651-138d-460e-b0f0-8f372fb06f5d)

You could obtain a code signing certificate from a trusted Certificate Authority (CA) and sign your executable.

**Comment by rodlie** [comment]
Click 'More info' and 'run anyway'.

> You could obtain a code signing certificate from a trusted Certificate Authority (CA) and sign your executable.

Yeah, that's not happening.
