### ISSUE TITLE
Pivot: support align (top/bottom/left/right) to self

### ISSUE THREAD

**Issue by eFe-Munoz** [friction2d/friction#263]
My proposal is to add in the animation palette an option for the pivot to be aligned with respect to the shape. 

This way with one click you can get the pivot to be placed for example centered and at the base of the object in two clicks.

This way of aligning pivots is very useful for animation, if you don't have to do it by hand and it is not very effective.

**Comment by rodlie** [comment]
> pivot to be aligned with respect to the shape

Please specify what should happen.

**Comment by rodlie** [comment]
https://github.com/friction2d/friction/issues/142#issuecomment-2416503891

@eFe-Munoz Ok, understand what you want.

**Comment by pgilfernandez** [comment]
+1

I also think this would be a nice feature update. It also happened to me to try to do what @eFe-Munoz explained and I ended up doing it manually...

**Comment by eFe-Munoz** [comment]
great news! happy new year.
