### ISSUE TITLE
Add plugin system

### ISSUE THREAD

**Issue by kaixoo** [friction2d/friction#268]
One of the main things people say about the software is that it's great, and that it could replace after effects in their workflow if it wasn't for the plugins. I don't know how AE plugins behave and if they could be implemented, but perhaps we could craft a plugin system (in the mid / long term).

**Comment by rodlie** [comment]
We have support for several plugin types, most have been disabled. We only allow [shader plugins](https://github.com/friction2d/friction-shader-plugins) for now.

OpenFX will at some point be added (v2+), outside of that I have no plans for more plugin systems.

**Comment by kaixoo** [comment]
For what reasons have they been disabled? Good to know there is an FX standard, does other software like AE follow it or no?

**Comment by rodlie** [comment]
> For what reasons have they been disabled?

* We have no documentation for developing plugins
* I will probably rewrite most of the plugin stuff
* Users are artists not developers, GLSL/JS is hard enough, I don't expect users to know C++ and how frictioncore works

We can open up for various plugins in the future, for now I don't see the need.

> Good to know there is an FX standard, does other software like AE follow it or no?

OpenFX is the VFX industry standard for plugins. I don't know what Adobe does, probably not.
