### ISSUE TITLE
Path / Difference behavior

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction#294]
It maybe be as you pretended to be but as it is at the contrary in Inkscape I just commenting it:

If you have 2 shapes and want to do a "difference boolean", that is, Path / Difference, the normal behavior in Inkscape (and other vector graphics softwares) is that the shape on top cuts the one below, but in Friction is at the contrary.
If I start with this arrangement (obviously the red rectangle is on top of the green circle):

<img width="379" alt="one" src="https://github.com/user-attachments/assets/f2e726c0-f369-4b4e-86e3-bf50d00ab40e">

The result is the following (blue shape):

<img width="372" alt="two" src="https://github.com/user-attachments/assets/ef9f499e-865b-4b48-99c9-41017e4c0fe0">

I see that Friction behavior is to keep the original shapes, which is acceptable and probably a good thing in some workflows, but what feels odd in the fact that the one below is the one that is cutting the one on top...

Is that known and is the way you want it to be?

Cheers

**Comment by rodlie** [comment]
You are correct, It does the opposite of what you would expect. Will take a look.

> I see that Friction behavior is to keep the original shapes

All options under `Path` will create a new path item, the original items are not touched.

A compromise could be a checkbox under the `Path` menu, "Keep original object(s)" with default on?

**Comment by pgilfernandez** [comment]
> All options under Path will create a new path item, the original items are not touched.
> 
> A compromise could be a checkbox under the Path menu, "Keep original object(s)" with default on?

I don't think leaving the original items is a bad idea "per se", it could be useful in some scenarios, but it would be even better to have that checkbox under the Path menu so that user can choose their preferred o behavior indeed.

**Comment by rodlie** [comment]
I could add the option, note that it will be default on as this is expected behavior from existing users.

**Comment by rodlie** [comment]
This should probably be fixed before v1.0.

Looking at the code it just takes selected boxes and apply in order.

https://github.com/friction2d/friction/blob/main/src/core/canvasselectedboxesactions.cpp#L703

**Comment by rodlie** [comment]
Just reverse the order? :smile: 
```
diff --git a/src/core/canvasselectedboxesactions.cpp b/src/core/canvasselectedboxesactions.cpp
index d609fef2..7800ca31 100644
--- a/src/core/canvasselectedboxesactions.cpp
+++ b/src/core/canvasselectedboxesactions.cpp
@@ -705,7 +705,8 @@ SmartVectorPath *Canvas::getPathResultingFromOperation(const SkPathOp& pathOp) {
     newPath->planCenterPivotPosition();
     SkOpBuilder builder;
     bool first = true;
-    for(const auto &box : mSelectedBoxes) {
+    const QList<BoundingBox*> boxes(mSelectedBoxes.rbegin(), mSelectedBoxes.rend());
+    for (const auto &box : boxes) {
         if(const auto pBox = enve_cast<PathBox*>(box)) {
             SkPath boxPath = pBox->getRelativePath();
             const QMatrix boxTrans = box->getRelativeTransformAtCurrentFrame();

```

**Comment by pgilfernandez** [comment]
Wow, it could be indeed.... tomorrow I'll test it

**Comment by rodlie** [comment]
Nice, commit merged into main.
