### ISSUE TITLE
[Feature request] Link image files

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction#298]
Hi,

The "Link" feature is fantastic to be able to edit your files externally while keeping the animation intact. I've seen it only works for SVG files and not for image files (PNG, JPEG, ...).

Could this feature be extended to image files as well?

Thanks!!

**Comment by rodlie** [comment]
Images are always external assets, so no need to link them, just import or drag and drop.

**Comment by pgilfernandez** [comment]
Oh, OK, I didn't realize about it... thanks!
