### ISSUE TITLE
GPU (Radeon/NVIDIA) AA issues

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#304]
So, this has been reported to me several times and is a known issue (see any release notes). But I never made an issue to track the progress/status.

### What's the problem?

Paths are not antialiased on some GPUs, creating bad preview/renders.

### How to replicate?

Add some text and zoom in, either is smooth/perfect or not ("k" is a good char to test with)

### GPUs affected?

* Modern NVIDIA cards on Windows and Linux
* Possible Radeon on Windows(?) - need feedback as I don't test or use Radeon

### GPUs that work?

* Intel GPUs work perfectly on Windows, macOS and Linux
* Radeon possible work on macOS/Linux (?) - need feedback from users

### How to fix?

I don't know.

**Comment by rodlie** [comment]
Just as a reference, Intel GPU:

![Screenshot from 2024-11-06 13-11-54](https://github.com/user-attachments/assets/1df67679-52d1-4f26-9b3d-353851301a19)

On NVIDIA (and possible Radeon) you will notice jagged lines on the k.

**Comment by rodlie** [comment]
## NVIDIA status

So, wasted yesterday testing NVIDIA cards, tested all kind of cards (20+ different cards). From laptops, desktops, Quadro, Geforce, Windows 10, Windows 11, various distros and a ton of different drivers.

### Conclusion

* OS does not matter
* Driver does not matter
* Kepler and Maxwell works perfectly fine
* Issue introduced in Pascal
* Issue still present in Turing

So, what does this mean? something changed/broke in Pascal.

**Comment by kroll-j** [comment]
![image](https://github.com/user-attachments/assets/d9f9ead5-f4c6-46a9-8e92-d1b385eb4a36)
This is on Linux with open source AMD drivers. There is antialiasing, but it looks a bit coarser to me, compared to the Intel screenshot. Maybe this driver uses a different AA method.

**Comment by rodlie** [comment]
This is identical to NVIDIA Pascal or newer.

**Comment by kroll-j** [comment]
![image](https://github.com/user-attachments/assets/2c62e975-dad5-48da-9da8-ea78eccfff23)
Again, AMD. Zoomed in. This looks to me like it could be oversampling (maybe 4x?) rather than proper antialiasing.

Reminds me of `glHint(GL_LINE_SMOOTH, GL_NICEST)` vs `glHint(GL_LINE_SMOOTH, GL_FASTEST)` in OpenGL immediate mode where the driver would be free to pick an implementation and results would vary depending on the driver and card. But that was ages ago. Not sure how the render path works in friction/skia.

**Comment by rodlie** [comment]
On NVIDIA I tested all sorts of OpenGL versions, tweaks, settings, oversampling etc etc, nothing changed. Only a downgrade of the actual GPU did something.

So, that's all I know and nothing I can do about it (as far as I know).

**Comment by rodlie** [comment]
Been looking through the skia src, there is **a lot** of workarounds etc for various GPU's and drivers... Seems like crappy drivers are the norm. So at least we know that this has to be resolved in skia (src/gpu/gl).

There are several commits in upstream skia I could backport, some Radeon related. If they actually fix anything... I don't know.

AA on Radeon does not seem to be fixable, the latest skia src has this disabled as far as I can see (we could enable and see what happens, but I assume the Chromium team has done proper testing).

**Comment by rodlie** [comment]
https://groups.google.com/g/skia-discuss/c/Kdh8_xVg7V8

**Comment by kroll-j** [comment]
"msaa=0" looks perfect, thanks!
