### ISSUE TITLE
[Feature request] Use IN and OUT as rendering range

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction#310]
The IN and OUT feature is so nice for previewing something inside Friction.
A nice improvement would be to use them as a "preselected range" when exporting/rendering to video. That way, you would have an option inside the rendering options that lets you choose the **Range** between "_whole scene_" or "_IN and OUT_".

Cheers

**Comment by rodlie** [comment]
That should be doable, was actually waiting for someone to request the feature ;)

Currently working on some UI enhancements, so it will have to wait until tomorrow.

**Comment by pgilfernandez** [comment]
Hehehe, great then.

> 
> Currently working on some UI enhancements, so it will have to wait until tomorrow (or tonight).

That would be amazingly fast... it's not usual that feature resquest are coded that fast. Thanks!!
