### ISSUE TITLE
[Feature request] Add IN and OUT and markers command actions in app menu

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction#311]
I like having IN and OUT (and clear both) and set/edit/clear markers in the contextual menu but I would add them as well in the global app menu, under "Scene". That is:

- Scene / Set IN
- Scene / Set OUT
- Scene / Clear IN/OUT
- Scene / Add Marker
- Scene / Edit Markers
- Scene / Clear Markers

It's just an UX petition, that way users may navigate the menus and find their shortcuts easier.

Cheers

**Comment by pgilfernandez** [comment]
BTW, I could probably do it and PR it... I need to investigate a little

**Comment by rodlie** [comment]
The command palette is your friend ;) but, I can add it to the scene menu.

**Comment by pgilfernandez** [comment]
> The [command palette](https://friction.graphics/releases/friction-100-beta1.html#command-palette) is your friend ;) but, I can add it to the scene menu.

Hey, it didn't come to my mind, you are right!
It would be nice to have them in the menus as well. It's not something for me, it's something for general users.

Thanks again!

**Comment by rodlie** [comment]
Fixed in https://github.com/friction2d/friction/commit/9837cff9e1e775c0c14ca670bedab952c94d56e7
