### ISSUE TITLE
Graph view lacks a way of zooming the time horizontally

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction#313]
The only way of zooming is the "fit vertical" but:

In the "keyframes timeline" you can do:

- middle mouse button: pan left/right
- ctrl/command + mouse scroll: zoom in/out

In the "graph timeline" you can do:

- middle mouse button: pan left/right/up/down
- ctrl/command + mouse scroll: zoom in/out VERTICALLY (center of zoom in the middle of your window)
- ctrl/command + alt + mouse scroll: zoom in/out VERTICALLY (center of zoom in the mouse pointer position)
- ...

Maybe I'm missing something but there is not an option to zoom in/out HORIZONTALLY while in the "graph timeline"

I would say that the UX way would be to set "ctrl/command + shift + mouse scroll"... but I don't know, maybe it's not the best way. What I really mean is that this feature is missing and it would be useful.

Thanks!

**Comment by rodlie** [comment]
So, just add ctrl+wheel to zoom? like this:


https://github.com/user-attachments/assets/0f7684eb-816b-4863-af1c-bacfe7357e07

**Comment by rodlie** [comment]
> also noticed that Alt+scrolling is behiwing strangely seemst o always scroll down . doies not seems like very suful feature to me 

Then don't use it ;) The timeline/graph does not use the Alt modifier for anything.

But Qt does(?): https://forum.qt.io/topic/120028/wheel-event-direction-changing-when-pressing-alt-key

> contrl+shif scrolling should zoom in anod out in both axies currently one is always ignored

ctrl+shift does nothing in the code, you either use ctrl or shift. What do you mean by both axies?

**Comment by adambelis** [comment]
i am very used to tring all modifiers since every app . Its not best us if if modifier does nothing useless other then defoult behavior :D .
  
  for ctrl+shift it is more of feature request
  
  
 I'm imagaging  something like scaling in time + in values ate the same time 
https://github.com/user-attachments/assets/08cbb69f-4e5d-4cb7-ba1c-775afa22d87a

**Comment by adambelis** [comment]
or i can open new issue so its less messy ?

**Comment by rodlie** [comment]
Sure, that also works.

**Comment by adambelis** [comment]
https://github.com/friction2d/friction/issues/320
