### ISSUE TITLE
macOS - Duplicating keyframes duplicates objects too

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction#357]
I thought it was fixed here https://github.com/friction2d/friction/commit/fdb445507f83e49cd8e040a62beb78f8175b7df2, but I see that cmd+D (duplicate) still suffers from this issue.
(It was originally explained here https://github.com/friction2d/friction/issues/324)

Thanks!

**Comment by pgilfernandez** [comment]
Already fixed in proposed PR 😉

**Comment by rodlie** [comment]
https://github.com/friction2d/friction/issues/324
