### ISSUE TITLE
Applying fill color with picker doesn't enable fills

### ISSUE THREAD

**Issue by prokoudine** [friction2d/friction#363]
1. Draw some circles with stroke and no fill
2. Select them
3. Enable the color picker tool
4. Hover something and left-click
5. New fills will be applied but not displayed, you have to go to the Fill'n'Stroke dock and click to enable fills to see the result

This bug does not affect strokes. Strokes work as expected.

**Comment by rodlie** [comment]
I know, if you use the color picker from the toolbar (F9) just the flat color is applied to fill/stroke for selected objects, we don't change anything else.

> This bug does not affect strokes. Strokes work as expected.

Works the same for stroke, if it's none (or not flat) nothing will "happen" (the flat color is still applied).

---

If can probably set fill/stroke to 'flat' if 'none', but we don't want that for other modes like gradient (then you should use the color picker in the 'fill and stroke' widget instead).

**Comment by rodlie** [comment]
Fixed in https://github.com/friction2d/friction/commit/d493062f61e5c71bb6cd2acffc321a8840da61f9 (will set flat if none).
