### ISSUE TITLE
I cant find Qt 5.15.3 on the open source version of Qt. 

### ISSUE THREAD

**Issue by AlmostMikhail** [friction2d/friction#389]
![cm](https://github.com/user-attachments/assets/55e5f8dc-9da0-4f6b-9d6a-68b649275154)

![y](https://github.com/user-attachments/assets/3f872e03-bf1d-4736-8a8e-06b2d5577e56)

Can I just install Qt version 6.2.0?

**Comment by kaixoo** [comment]
Try to install it from here: https://github.com/miurahr/aqtinstall

Assuming windows 64 bits: `aqt install-qt windows desktop 5.15.16 x86_64-pc-windows-gnu`

**Comment by kaixoo** [comment]
Ignore my previous comment, it was more complicated than what you were doing

**Comment by rodlie** [comment]
Friction SDK: https://github.com/friction2d/friction-sdk/releases/download/v1.0.0/friction-sdk-1.0.0-windows-x64.7z

Extract to Friction src folder.

[CMake](https://github.com/Kitware/CMake/releases/download/v3.31.3/cmake-3.31.3-windows-x86_64.msi) and [Visual Studio 2017 Build Tools](https://aka.ms/vs/15/release/vs_buildtools.exe) are needed.

Then start the "Developer something" command prompt for VS2017:

```
set SDK_DIR=%cd%\sdk
set PATH=%ProgramFiles%\CMake\bin;%SDK_DIR%\bin;%PATH%

mkdir build
cd build

cmake -G "Visual Studio 15 2017" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%SDK_DIR% -DBUILD_ENGINE=OFF ..

cmake --build . --config Release
```
