### ISSUE TITLE
Menu not working on full screen (Friction 0.9.3, Windows 11 22H2)

### ISSUE THREAD

**Issue by lenildoleite** [friction2d/friction#55]
When in full screen mode, the menu itens on the top bar doesn't work, either with mouse or keyboard. keyboard shortcuts seems to work fine, as we can press f11 to go back to windowed mode and menu works fine.

**Comment by rodlie** [comment]
Just tested on a Windows 11 laptop (Intel gpu), and the menu bar works in full screen, but it flashes the screen once when you enter/leave.

But on a workstation running Windows 10 and NVIDIA I can replicate the issue.

I do not have this issue on Linux.

This is probably related to Qt (third-party). An upgrade might fix the issue. I can check tomorrow.

Thanks for the report :+1:

**Comment by lenildoleite** [comment]
Glad to help.
I am running friction on a laptop with a ryzen 7 5800 cpu (nvidia 3060 gpu), and do not experience these screenflashes when entering/leaving fullscreen.

**Comment by rodlie** [comment]
It's a known issue on Windows (https://doc.qt.io/qt-5.15/windows-issues.html#fullscreen-opengl-based-windows & https://phabricator.kde.org/D20657).

Tested the workaround, it works :+1: 

The next Windows build/release will include a fix for full screen.
