### ISSUE TITLE
Text Layer goes blank after selecting multiple layers

### ISSUE THREAD

**Issue by axiomgraph** [friction2d/friction#61]
OS Ubuntu 22.04
As you can see when I select the second layer. the text layer becomes blank. 
[Screencast from 20-08-23 12:26:07 PM IST.webm](https://github.com/friction2d/friction/assets/68183694/15bdffbc-32dc-49a7-bda2-1134ec29d34d)

**Comment by rodlie** [comment]
It's a known issue that will be fixed before 0.9.4 release.

I think I introduced the issue when I added the new font widget, anyway, it will be fixed.

**Comment by rodlie** [comment]
If you want to test stuff before release (this is a snapshot of main):

[friction-20230820-main-5b43b0d3-ubuntu22.04.deb.zip](https://github.com/friction2d/friction/files/12388647/friction-20230820-main-5b43b0d3-ubuntu22.04.deb.zip)
