### ISSUE TITLE
Windows HiDPI issues

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#68]
HiDPI on Windows is completely broken.

* Tested Qt 5.12.12
* Tested Qt 5.12.12 + Krita patches
* Tested Qt 5.15.10

**Comment by rodlie** [comment]
For reference (125% display scaling):

## Ubuntu (22.04)

![Screenshot from 2023-09-03 01-31-21](https://github.com/friction2d/friction/assets/34516798/fb537b5b-8587-4963-8419-2820477f1aa2)

## Windows (10)

![friction-windows-hidpi-125](https://github.com/friction2d/friction/assets/34516798/81778254-bb15-4023-8ff7-09fa304354a9)

**Comment by NothingHereIsReal** [comment]
I can confirm on Windows 10. Also, clickable regions (for example setting up gradients) appear to be off. Clicking higher and further to the right seems to work but is not aligned with UI elements. This might be to do with using a scaled screen. I'm on a 4K monitor with a scaling of 150%.

**Comment by rodlie** [comment]
Yes, hidpi on Windows is broken. Will start working on it this weekend and should be resolved by the next release.

**Comment by rodlie** [comment]
Got something usable:
![friction-hidpi-ok](https://github.com/friction2d/friction/assets/34516798/12124048-51fd-4d47-9ea0-9495677af6d7)

Will make a snapshot for people to test when done.

**Comment by rodlie** [comment]
Please test https://github.com/friction2d/friction/releases/tag/v0.9.5-beta1

**Comment by NothingHereIsReal** [comment]
I've just spent some time going through the beta and it all works fine as far as I can tell. The click "offset" from the previous build is now working correctly.
