### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#72]
Some want it, means more maintenance.... Not a priority.

**Comment by rodlie** [comment]
0.9.5 will feature new Linux binaries, they are universal and can be repackaged to any standard.

So, to make a flatpak just repackage our portable tarball as done in Natron: https://github.com/flathub/fr.natron.Natron

I don't have time to do anything with this, but if anyone want to help feel free to do something about it.

**Comment by rodlie** [comment]
Good news!

Had some spare time and have a working Friction 0.9.5rc1 flatpak, seems to work just fine (it's just a re-package of portable). Will of course need to figure out how to submit it to flathub etc.

**Comment by rodlie** [comment]
Will submit to flathub when 0.9.5 is done.

**Comment by pedropaulosuzuki** [comment]
> Will submit to flathub when 0.9.5 is done.

Couldn't find it on [Flathub](https://flathub.org/apps/search?q=Friction). According to [v0.9.6 RC1](https://github.com/friction2d/friction/releases/tag/v0.9.6-rc1), it seems that flatpak builds were canceled. So that means there are no Flatpak releases going forward, is that right?

**Comment by rodlie** [comment]
Yes, sorry about the confusion. Flatpak is EOL, maintaining it will be too much work, unless we do a repack of the portable (as in Natron)?

AppImage, RPM and portable should handle most use cases.

**Comment by yotamguttman** [comment]
is there a way users can get notified when you release a new appimage? since we don't have auto updates if we don't get this programme of flathub. maybe a newsletter or even an in-app notification with a download now link when a new version is pushed

**Comment by rodlie** [comment]
> is there a way users can get notified when you release a new appimage? since we don't have auto updates if we don't get this programme of flathub. maybe a newsletter

* https://github.com/orgs/friction2d/discussions/categories/announcements
* https://friction.graphics/news/
* https://friction.graphics/feed.xml
* https://floss.social/@friction

> or even an in-app notification with a download now link when a new version is pushed

No, that requires network access and SSL (a security issue).

**Comment by rodlie** [comment]
> No, that requires network access and SSL (a security issue).

Actually, we still support http://, so I could implement a version check that don't need https:// (ssl).
