### ISSUE TITLE
Top Menus Doesn't Shows On Full Screen Mode In Win11

### ISSUE THREAD

**Issue by freewarecamp** [friction2d/friction#74]
after going to full screen mode the top menus doesn't shows (after going to full screen mode recording had some problems when a new window shows up for new project/scene it became black)
 
https://github.com/friction2d/friction/assets/86367188/1a1f80fd-1f87-4c0f-8097-37e06eea7a2e

another problem is when right click to an object on the properties panel the first option gets automatically ticked which is kind of annoying

**Comment by rodlie** [comment]
I fixed full screen on Windows in 0.9.4.

**Comment by freewarecamp** [comment]
Sorry I didn't notice the new release. Thank you for fixing it
