### ISSUE TITLE
Scene / fps presets not visible by default even when enabled

### ISSUE THREAD

**Issue by prokoudine** [friction2d/friction#92]
When you run the new version after having used 0.9.4 or earlier releases, scene and frame rate presets are not visible by default even though they are enabled by default. I had to tick the checkboxes off and back on, then restart the program. I guess there's something fishy going on in the code for reading program's configuration.

**Comment by rodlie** [comment]
Yes, the default values has not been set yet.

I'm also a bit unsure what should be on by default.
