### ISSUE TITLE
Incorrect timeline rendering of video's position

### ISSUE THREAD

**Issue by prokoudine** [friction2d/friction#94]
When I DnD a video file to the timeline, its start (when zoomed in close enough) is rendered with an offset to the 0 position:

![image](https://github.com/friction2d/friction/assets/57467/6ee8e889-b6f6-4119-8798-d9c53d425052)

Could this be a HiDPI bug?

**Comment by rodlie** [comment]
> Could this be a HiDPI bug?

Probably, I don't have this issue (I don't scale the display). Will check

**Comment by rodlie** [comment]
Confirmed, seems to be a zoom issue (not hidpi).

**Comment by rodlie** [comment]
Should work now.
