### ISSUE TITLE
0.9.5 release status

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#96]
Hi,

The planned release this past weekend did not happen, mostly due to last minute issues (a good thing, as they were resolved).

I did however plan to release 0.9.5 on the 13th, but after some testing on a Windows 11 laptop with 150% scaling I decided last night to delay the release. Why? HiDPI aka display scaling is default on most Windows laptops at the moment, and I'm not happy with how Friction and Qt in general behaves with display scaling (font size vs. icon size).

Solution? Yeah, kind of... more like a workarounds. I will "fix" the issue during this week and be ready for release most likely on Saturday (18th).

**Comment by dadoprom** [comment]
Perfect, take your time, no hurry... but still I can not wait :)
